# Generated by Django 5.1.4 on 2026-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.TextField(db_index=True)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, db_index=True, max_length=50)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField(blank=True)),
                ('path', models.TextField(blank=True)),
                ('size', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='SyncMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
        ),
    ]
